if [ ! "$_PORTABLEMODE_INCLUDED_" == "1" ]; then 
_PORTABLEMODE_INCLUDED_=1

function feature_mode-portable() {
	FEAT_NAME="mode-portable"
	FEAT_LIST_SCHEMA="nested"
	FEAT_DEFAULT_VERSION=nested
	FEAT_DEFAULT_ARCH=

	FEAT_BUNDLE=NESTED
}

function feature_mode-portable_nested() {
	FEAT_VERSION=nested
	
	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=


	FEAT_BUNDLE_ITEM="$FEAT_MODE_PORTABLE_SCHEMA"

	FEAT_ENV_CALLBACK=
	FEAT_BUNDLE_CALLBACK=

	FEAT_INSTALL_TEST=
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin
	
}



fi