if [ ! "$_AUTOCONF_INCLUDED_" == "1" ]; then 
_AUTOCONF_INCLUDED_=1


function feature_autoconf() {
	FEAT_NAME=autoconf
	FEAT_LIST_SCHEMA="2_69:source"
	FEAT_DEFAULT_VERSION=2_69
	FEAT_DEFAULT_ARCH=
	FEAT_DEFAULT_FLAVOUR="source"
}

function feature_autoconf_2_69() {
	FEAT_VERSION=2_69
	# TODO NEED : perl 5.6 and M4
	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
	FEAT_SOURCE_URL_FILENAME=autoconf-2.69.tar.gz
	FEAT_SOURCE_URL_PROTOCOL=HTTP_ZIP


	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_URL_PROTOCOL=

	FEAT_SOURCE_CALLBACK=feature_autoconf_2_69_patch
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=

	
	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/autoconf
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}

function feature_autoconf_2_69_patch() {
	#TODO : really need this ?
	#AUTO_INSTALL_CONF_FLAG_POSTFIX="--docdir=$INSTALL_DIR/share/doc/automake-1.14"
	AUTO_INSTALL_CONF_FLAG_POSTFIX=
}

function feature_autoconf_install_source() {
	INSTALL_DIR="$FEAT_INSTALL_ROOT"
	SRC_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-src"
	
	__get_resource "$FEAT_NAME" "$FEAT_SOURCE_URL" "$FEAT_SOURCE_URL_PROTOCOL" "$SRC_DIR" "DEST_ERASE STRIP"

	#__set_toolset "CUSTOM" "CONFIG_TOOL configure BUILD_TOOL make"
	__set_toolset "STANDARD"

	AUTO_INSTALL_CONF_FLAG_PREFIX=
	AUTO_INSTALL_CONF_FLAG_POSTFIX=	
	AUTO_INSTALL_BUILD_FLAG_PREFIX=
	AUTO_INSTALL_BUILD_FLAG_POSTFIX=

	__feature_callback

	__auto_build "$FEAT_NAME" "$SRC_DIR" "$INSTALL_DIR"
	
}

fi