if [ ! "$_HTOP_INCLUDED_" == "1" ]; then 
_HTOP_INCLUDED_=1


function feature_htop() {
	FEAT_NAME=htop

	if [ "$STELLA_CURRENT_PLATFORM" == "darwin" ]; then

		FEAT_LIST_SCHEMA=
		FEAT_DEFAULT_VERSION=
		FEAT_DEFAULT_ARCH=
		FEAT_DEFAULT_FLAVOUR=
	fi
	if [ "$STELLA_CURRENT_PLATFORM" == "linux" ]; then
		FEAT_LIST_SCHEMA="1_0_3:source"
		FEAT_DEFAULT_VERSION=1_0_3
		FEAT_DEFAULT_ARCH=
		FEAT_DEFAULT_FLAVOUR="source"
	fi

}

function feature_htop_1_0_3() {
	FEAT_VERSION=1_0_3


	FEAT_SOURCE_DEPENDENCIES="ncurses"
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=http://hisham.hm/htop/releases/1.0.3/htop-1.0.3.tar.gz
	FEAT_SOURCE_URL_FILENAME=htop-1.0.3.tar.gz
	FEAT_SOURCE_URL_PROTOCOL=HTTP_ZIP

	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_URL_PROTOCOL=

	FEAT_SOURCE_CALLBACK=feature_htop_link
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=

	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/htop
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}

function feature_htop_link() {
	__link_feature_library "ncurses" "FORCE_DYNAMIC"
}


function feature_htop_install_source() {
	INSTALL_DIR="$FEAT_INSTALL_ROOT"
	SRC_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-src"
	
	__get_resource "$FEAT_NAME" "$FEAT_SOURCE_URL" "$FEAT_SOURCE_URL_PROTOCOL" "$SRC_DIR" "DEST_ERASE STRIP FORCE_NAME $FEAT_SOURCE_URL_FILENAME"


	AUTO_INSTALL_CONF_FLAG_PREFIX=
	#AUTO_INSTALL_CONF_FLAG_POSTFIX="--disable-dependency-tracking"
	AUTO_INSTALL_CONF_FLAG_POSTFIX=
	AUTO_INSTALL_BUILD_FLAG_PREFIX=
	AUTO_INSTALL_BUILD_FLAG_POSTFIX=

	__feature_callback

	__auto_build "$FEAT_NAME" "$SRC_DIR" "$INSTALL_DIR" "CONFIG_TOOL configure"
	

	

}


fi
