if [ ! "$_ATOP_INCLUDED_" == "1" ]; then 
_ATOP_INCLUDED_=1

# TODO NOT FINISHED

function feature_atop() {
	FEAT_NAME=atop
	FEAT_LIST_SCHEMA="2_2_3:source"
	FEAT_DEFAULT_VERSION=2_2_3
	FEAT_DEFAULT_ARCH=
	FEAT_DEFAULT_FLAVOUR="source"
}

function feature_atop_2_2_3() {
	FEAT_VERSION=2_2_3


	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=http://www.atoptool.nl/download/atop-2.2-3.tar.gz
	FEAT_SOURCE_URL_FILENAME=atop-2.2-3.tar.gz
	FEAT_SOURCE_URL_PROTOCOL=HTTP_ZIP

	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_URL_PROTOCOL=

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=

	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/atop
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}



function feature_atop_install_source() {
	INSTALL_DIR="$FEAT_INSTALL_ROOT"
	SRC_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-src"
	
	__get_resource "$FEAT_NAME" "$FEAT_SOURCE_URL" "$FEAT_SOURCE_URL_PROTOCOL" "$SRC_DIR" "DEST_ERASE STRIP"

	cd "$SRC_DIR"
	make all
	#__auto_build "atop" "$FEAT_SOURCE_URL_FILENAME" "$FEAT_SOURCE_URL" "$FEAT_SOURCE_URL_PROTOCOL" "$SRC_DIR" "$INSTALL_DIR" "CONFIG_TOOL configure BUILD_TOOL make SOURCE_KEEP"
	

}


fi
