if [ ! "$_M4_INCLUDED_" == "1" ]; then 
_M4_INCLUDED_=1


function feature_m4() {
	FEAT_NAME=m4
	FEAT_LIST_SCHEMA="1_4_17/source"
	FEAT_DEFAULT_VERSION=1_4_17
	FEAT_DEFAULT_ARCH=
	FEAT_DEFAULT_FLAVOUR="source"
}

function feature_m4_1_4_17() {
	FEAT_VERSION=1_4_17

	FEAT_SOURCE_URL=http://mirrors.ibiblio.org/gnu/ftp/gnu/m4/m4-1.4.17.tar.gz
	FEAT_SOURCE_URL_FILENAME=m4-1.4.17.tar.gz
	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_CALLBACK=

	FEAT_DEPENDENCIES=
	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/m4
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

	FEAT_BUNDLE_LIST=
}

function feature_m4_install_source() {
	INSTALL_DIR="$FEAT_INSTALL_ROOT"
	SRC_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-src"
	BUILD_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-build"
	
	AUTO_INSTALL_FLAG_PREFIX=
	AUTO_INSTALL_FLAG_POSTFIX=

	__auto_install "configure" "m4" "$FEAT_SOURCE_URL_FILENAME" "$FEAT_SOURCE_URL" "$SRC_DIR" "$BUILD_DIR" "$INSTALL_DIR" "STRIP"
}

fi