if [ ! "$_LFTP_INCLUDED_" == "1" ]; then 
_LFTP_INCLUDED_=1

# TODO DO NOT WORK ON DARWIN, cause it needs gnu readline
# TODO review openssl link
function feature_lftp() {
	FEAT_NAME=lftp
	FEAT_LIST_SCHEMA="4_6_3:source"
	FEAT_DEFAULT_VERSION=4_6_3
	FEAT_DEFAULT_ARCH=
	FEAT_DEFAULT_FLAVOUR="source"
}

function feature_lftp_4_6_3() {
	FEAT_VERSION=4_6_3
	
	# openssl, gnu readline
	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=http://lftp.yar.ru/ftp/lftp-4.6.3a.tar.xz
	FEAT_SOURCE_URL_FILENAME=lftp-4.6.3a.tar.xz
	FEAT_SOURCE_URL_PROTOCOL=
	
	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_URL_PROTOCOL=

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=

	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/lftp
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}

function feature_lftp_install_source() {
	INSTALL_DIR="$FEAT_INSTALL_ROOT"
	SRC_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-src"
	BUILD_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-build"
	
	AUTO_INSTALL_FLAG_PREFIX=
	AUTO_INSTALL_FLAG_POSTFIX="--disable-dependency-tracking --with-openssl=$(brew --prefix openssl)"

	__auto_install "configure" "lftp" "$FEAT_SOURCE_URL_FILENAME" "$FEAT_SOURCE_URL" "$SRC_DIR" "$BUILD_DIR" "$INSTALL_DIR" "STRIP"
}

fi