if [ ! "$_kafka_INCLUDED_" == "1" ]; then 
_kafka_INCLUDED_=1



function feature_kafka() {
	FEAT_NAME=kafka
	FEAT_LIST_SCHEMA="0_9_0_0:binary"
	FEAT_DEFAULT_VERSION=0_9_0_0
	FEAT_DEFAULT_ARCH=
	FEAT_DEFAULT_FLAVOUR="binary"
}


function feature_kafka_0_9_0_0() {
	FEAT_VERSION=0_9_0_0
	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=
	FEAT_SOURCE_URL_FILENAME=
	FEAT_SOURCE_URL_PROTOCOL=

	FEAT_BINARY_URL=https://www.apache.org/dyn/closer.cgi?path=/kafka/0.9.0.0/kafka_2.11-0.9.0.0.tgz
	FEAT_BINARY_URL_FILENAME=kafka_2.11-0.9.0.0.tgz
	FEAT_BINARY_URL_PROTOCOL=HTTP_ZIP

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=


	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/kafka
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}

function feature_kafka_install_binary() {
	__get_resource "$FEAT_NAME" "$FEAT_BINARY_URL" "$FEAT_BINARY_URL_PROTOCOL" "$FEAT_INSTALL_ROOT" "STRIP"

}


fi
