env:
  global:
    - PYTHONUNBUFFERED=yes
    - secure: "TyC3F7uBmd4iWLpUyhIDkpRfbhPUmRqFeFhr12VSHfzODQfeLBqB9hHMhhjVLlk1gsQwIXzNDY2X82U83d4gG0X+SEPDUpTimuWc/GJoJLQL4+uyfpS8seQWnxa7ZXkZrUdKb2owHtx+0ESzZwfOg+pd0OxoMenK9bcGo3hZtkk="

# apt-get is only available to the Ubuntu tests (os: linux)
# the other tests (os: osx) uses Homebrew to install shell
# dependencies and is done in ./utils/travis-install.sh
addons:
  apt:
    packages:
      - zsh
      - csh
      - tcsh
      - posh
      - ksh


git:
  depth: 100


cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


matrix:
  include:
    - env: PYTHON_VERSION=3.6 SUDO=true
      sudo: true
      language: generic
      os: linux
    - env: PYTHON_VERSION=3.4
      sudo: false
      language: generic
      os: linux
    - env: PYTHON_VERSION=2.7
      sudo: false
      language: generic
      os: linux
    - env: FLAKE8=true
      sudo: false
      language: python
      python: '3.5'
      os: linux
    - env: PYTHON_VERSION=3.6
      sudo: false
      language: generic
      os: osx
    - env: PYTHON_VERSION=3.6 CONDA_BUILD=2.1.3
      sudo: false
      language: generic
      os: linux
  allow_failures:
    - os: osx

install:
  - source ./utils/travis-install.sh

script:
  - source ./utils/travis-script.sh

sudo: false

after_success:
  - ~/miniconda/bin/pip install codecov coveralls scrutinizer-ocular
  - codecov --env PYTHON_VERSION
  - coveralls || true
  - ocular || true
